### ISSUE TITLE
[alpha - issue] 마이페이지 소개가 긴 경우 칸을 벗어나는 문제

### ISSUE THREAD

**Issue by Sungho95** [indiego-project/indiego#145]
## 문제
마이페이지 프로필 수정하기에서 소개를 길게 작성한 경우 칸을 벗어나는 문제가 발생합니다.
![12121](https://user-images.githubusercontent.com/80394894/236199159-bfe0ea8c-69dc-4b54-be75-e9383f2e3a84.png)

**Comment by Biewoom** [comment]
되게 길게 하니, 페이지를 뚫게 되는군요.

![image](https://user-images.githubusercontent.com/40663178/236605971-2de10ce4-2ccf-4dc4-b4b4-f679e284ba40.png)

### 해결책
- 작성할 때부터 수를 제한을 하는 게 좋을 것 같습니다.
