### ISSUE TITLE
[Alpha - Issue] 공연 작성시, 데이터가 백엔드 유효성 검사를 통과하지 못할 시 로그인이 만료되었다고 표시되는 오류

### ISSUE THREAD

**Issue by yeonhwan** [indiego-project/indiego#152]
### [문제 상황]
공연 작성시, 클라이언트에서 유효성 검사 피드백이 제대로 이루어지지 않음
백엔드 유효성 검사를 통과하지 못할 시 ,로그인 시간이 만료되지 않았음에도 로그인이 만료되었다고 표시됨

### 클라이언트 유효성 검사에는, 올바른 유효성 피드백이 표시되고, 서버의 response message를 제대로 반영해야함

1. 공연 제목에 대한 유효성 검사 (Not Nulll, 글자 수 제한)
2. 공연 포스터에 대한 유효성 검사 (Not Null, 용량 제한)
3. 공연 내용에 대한 유효성 검사 (Not Null, 글자 수 제한)
4. 공연 지역에 대한 유효성 검사 (지역에 서울이 포함되어있지 않으면 유효하지 않도록 함)
5. 공연 상세 지역에 대한 유효성 검사 (Not Null, 글자 수 제한)
6. 공연 시간에 대한 유효성 검사 (input 타입을 시간으로 변경)
7. 공연 좌석에 대한 유효성 검사 (input 타입을 number 로 변경, 최소 - 최대 좌석 수 지정)
8. 공연 가격에 대한 유효성 검사 (input 타입을 number 로 변경, 최소 - 최대 가격 지정)
9. 공연 상세 설명에 대한 유효성 검사 (Not Null, 글자 수 제한)

### [예상 이유]
클라이언트 유효성 피드백 및 에러 핸들링이 제대로 작성되지 않았기 때문에 발생하는 오류 인듯함

**Comment by Biewoom** [comment]
이거 정말 시급한 거 같습니다..
기껏 다 작성하고, 이거 때문에 업로드가 안되면.. 너무 화가 나네요..
