### ISSUE TITLE
[Alpha - Issue] 공연 작성 관련, 서버 Error 메세지를 클라이언트에 좀 더 명확하게 보내줄 필요성이 존재

### ISSUE THREAD

**Issue by yeonhwan** [indiego-project/indiego#153]
### [문제 상황]
공연 작성-수정 시, 클라이언트에서 서버로 잘못된 형식의 데이터가 전달되었을 때  Error 메세지를 클라이언트에 좀 더 명확하게 보내줄 필요성이 존재
현재 405(Methods Not Allowed)로 일괄적으로 날아오는 부분이 존재 (명확하게 어떤 상황에서 오류가 나는지 판단 불가)
ex) 상세주소 필드에, 아무 데이터나 넣었을 때 혹은 마포구로 주소가 설정되었을 때 ? 

### [의견 제시]
1. 각각의 유효성 검사에 대해, status 404  + error 메세지 (어떠한 유효성 검사를 통과하지 못했는 지) 가 필요해보입니다.

**Comment by Biewoom** [comment]
위 상황에서 BE 에서 descritive 한 Error messge를 남기는 부분 좋지만,
FE <-> BE 에서의 Error message는 Error message에  필요이상 DB 정보를 담지 않도록 조심해야합니다.
이미 아시겠지만, 그런 경우  SQL injection 위험에 노출 될 수 있기 때문입니다. ( ex: https://charming-kyu.tistory.com/18 )
( 저희 API는 이것까지..는 고려하지 않아도 될 거같긴하지만...)

저희 내부 환경까지만 Message를 자세히 출력하고, Prod 에는 이 기능을 제공하지 않는 식으로 푸는건 어떨까요?

**Comment by yeonhwan** [comment]
좋습니다! SQL injection 까지는 전혀 생각을 못했었는데 그런 위험이 있기도 하는군요! 시몬님 말씀대로 클라이언트 유효성 검사가 구현될 때까지만 에러메세지를 분명히 하고 그 이후에는 (베타 테스트 및 이후 Prod 환경) 제거해도 좋을 것 같습니다!
