### ISSUE TITLE
[alpha - issue] 공연 작성하기 양식을 벗어났을 경우 발생하는 문제

### ISSUE THREAD

**Issue by Sungho95** [indiego-project/indiego#171]
## 문제
발생하는 곳
1. 공연명
2. 상세 주소
3. 상세 설명
입력공간을 매우 길게 작성했을 경우 에러 발생

![에러1](https://user-images.githubusercontent.com/80394894/236673847-c9fc9656-4d5a-48ae-a201-6351c7027faa.PNG)
![에러2](https://user-images.githubusercontent.com/80394894/236674046-9d39e39b-bae0-488a-bacc-9d456cf391bd.PNG)
![에러3](https://user-images.githubusercontent.com/80394894/236674048-de23b030-be5f-4977-984e-88897bf276db.PNG)

**Comment by Biewoom** [comment]
#152  중복 이슈로 close 합니다
