### ISSUE TITLE
[alpha - issue] 일반 유저 예매하기

### ISSUE THREAD

**Issue by kimjeonghui** [indiego-project/indiego#174]
## 문제
1. 일반 유저가 예매 버튼을 클릭할 시 별도의 안내가 없음
2. 일반 유저가 커뮤니티 글에 댓글 작성 시도할 경우 별도의 안내가 없음

**Comment by Biewoom** [comment]
1,2 둘다 예매버튼 클릭시 => 알림창 + 로그인 페이지
